# Generated by Django 3.0.8 on 2020-07-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('uname', models.CharField(max_length=100)),
                ('unasc', models.DateField(blank=True)),
                ('uteste', models.CharField(choices=[('RT-PCR', 'RT-PCR'), ('Sorologia', 'Sorologia'), ('Teste Rápido - Antígenos', 'Teste Rápido - Antígenos'), ('Teste Rápido - Anticorpos', 'Teste Rápido - Anticorpos')], default='RT-PCR', max_length=100)),
                ('uresultado', models.BooleanField(choices=[(False, 'Negativo'), (True, 'Positivo')])),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
