# Generated by Django 3.0.3 on 2020-07-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='eid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ename',
            new_name='uname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='econtact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='eemail',
        ),
        migrations.AddField(
            model_name='user',
            name='unasc',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uresultado',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uteste',
            field=models.CharField(default='1111', max_length=100),
            preserve_default=False,
        ),
    ]
