# Generated by Django 3.0.3 on 2020-07-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200723_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unasc',
            field=models.DateField(blank=True, null=True),
        ),
    ]
