# Generated by Django 3.0.3 on 2020-07-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200724_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unasc',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='uresultado',
            field=models.BooleanField(choices=[('TRUE', 'Positivo'), ('FALSE', 'Negativo')], default='Negativo', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='uteste',
            field=models.CharField(choices=[('RT-PCR', 'RT-PCR'), ('Sorologia', 'Sorologia'), ('Teste Rápido - Antígenos', 'Teste Rápido - Antígenos'), ('Teste Rápido - Anticorpos', 'Teste Rápido - Anticorpos')], default='RT-PCR', max_length=100),
        ),
    ]
